package org.hyw.tools.generator.cmd;

import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Enumeration;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Scanner;

import org.apache.commons.io.IOUtils;
import org.apache.commons.lang3.StringUtils;
import org.hyw.tools.generator.Generator;
import org.hyw.tools.generator.cmd.enums.ValueType;
import org.hyw.tools.generator.conf.GlobalConf;
import org.hyw.tools.generator.conf.dao.DataSourceConf;
import org.hyw.tools.generator.constants.ValidationConstants;
import org.hyw.tools.generator.enums.Component;
import org.hyw.tools.generator.enums.db.DBType;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * 命令行代码生成器驱动类 - 优化向导版
 */
public class CmdGenerator {
	private static final Logger logger = LoggerFactory.getLogger(CmdGenerator.class);
	private static final int MAX_RETRY = 3;

	private static final String ARG_DB_PASSWORD = "--db-password";
	private static final String ARG_DB_NAME = "--db-name";
	private static final String ARG_QUICK = "--quick";
	private static final String ARG_HELP = "--help";

	public static void main(String[] args) {
		Map<String, String> argMap = parseArgs(args);
		if (argMap.containsKey(ARG_HELP)) {
			printHelp();
			return;
		}

		boolean quickMode = argMap.containsKey(ARG_QUICK);

		try (Scanner scanner = new Scanner(System.in)) {
			Generator generator = Generator.getInstance();

			if (!quickMode)
				displayWelcomeMessage();

			// 1. 初始化全局项目配置
			initGlobalProjectConf(generator.getGlobal(), scanner, quickMode);

			// 2. 初始化数据源
			DataSourceConf ds = generator.getDataSource();
			if (quickMode)
				applyCommandLineArgsToDataSource(ds, argMap);
			boolean isAutoCreated = initDataSourceConf(ds, scanner, argMap, quickMode);

			// 3. 业务配置 (依赖数据库)
			initTableSelectionConf(generator, scanner, isAutoCreated, quickMode);

			// 4. 执行生成
			executeGeneration(generator);

		} catch (Exception e) {
			logger.error("程序运行异常:", e);
			System.exit(1);
		}
	}

	private static void initGlobalProjectConf(GlobalConf global, Scanner scanner, boolean quickMode) {
		if (quickMode)
			return;

		System.out.println("\n=== 第一步：项目基本配置 ===");
		global.setOutputDir(ask(scanner, "生成目录", ValueType.REQUIRE_SINGLE, global.getOutputDir()));
		global.setRootPackage(ask(scanner, "项目根包名", ValueType.REQUIRE_SINGLE, global.getRootPackage()));
		global.setFileOverride(
				Boolean.parseBoolean(ask(scanner, "是否覆盖已有文件", ValueType.REQUIRE_SINGLE, "true", "false")));
		global.setDescription(ask(scanner, "项目描述", ValueType.NOT_REQUIRE_SINGLE, "Generated by CmdGenerator"));

		String modules = ask(scanner, "工程模块(逗号分隔)", ValueType.REQUIRE_MULTIPLE, String.join(",", global.getModules()));
		global.setModules(modules.split(","));
		selectComponentPreset(global, scanner);
	}

	private static boolean initDataSourceConf(DataSourceConf ds, Scanner scanner, Map<String, String> argMap,
			boolean quickMode) throws SQLException {
		if (quickMode) {
			if (StringUtils.isBlank(ds.getPassword())) {
				System.err.println("错误：快速模式必须提供密码！使用 --db-password 参数");
				System.exit(1);
			}
			// 接收参数数据库名，如参数为空则默认ds.getDbName()
			String dbName = argMap.get(ARG_DB_NAME);
			if (StringUtils.isBlank(dbName)) {
				dbName = ds.getDbName();
			}
			// 设置数据库名（会更新URL）
			ds.setDbName(dbName);
			// 判断数据库不存在的话就创建
			return ds.createDatabase(dbName);
		}
		return setupDataSourceInteractive(ds, scanner);
	}

	private static void initTableSelectionConf(Generator generator, Scanner scanner, boolean isAutoCreated,
			boolean quickMode) throws Exception {
		List<String> tables = generator.getAllTableNames();

		if ((tables == null || tables.isEmpty()) && !isAutoCreated) {
			if (generator.getDataSource().getDBType() == DBType.MYSQL) {
				System.out.println("检测到数据库为空，尝试导入示例 SQL...");
				if (executeAllSqlScripts(generator.getDataSource().getCon())) {
					tables = generator.getAllTableNames();
				}
			}
		}

		if (tables == null || tables.isEmpty()) {
			System.err.println("错误：数据库中没有任何表，无法生成代码！");
			System.exit(1);
		}

		if (quickMode) {
			generator.getGlobal().setInclude(tables.toArray(new String[0]));
			return;
		}

		System.out.println("\n=== 第三步：选择生成范围 ===");
		System.out.println("当前可用表: " + String.join(", ", tables));
		String tabInput = ask(scanner, "输入表名 (* 全部, 多表逗号分隔)", ValueType.REQUIRE_SINGLE_OR_MULTIPLE, "*");

		generator.getGlobal().setInclude("*".equals(tabInput) ? tables.toArray(new String[0]) : tabInput.split(","));

		String prefix = ask(scanner, "移除表前缀 (如有)", ValueType.NOT_REQUIRE_SINGLE, "");
		if (StringUtils.isNotBlank(prefix)) {
			generator.getGlobal().setTablePrefix(prefix.split(","));
		}
	}

	private static boolean setupDataSourceInteractive(DataSourceConf ds, Scanner scanner) throws SQLException {
		for (int i = 1; i <= MAX_RETRY; i++) {
			System.out.println("\n=== 第二步：配置数据库连接 (尝试 " + i + "/" + MAX_RETRY + ") ===");
			String typeStr = ask(scanner, "数据库类型", ValueType.REQUIRE_SINGLE, DBType.getDbNames());
			DBType dbType = DBType.getDbType(typeStr);

			// 解决编译错误：使用明确的方法调用
			String ip = scanner(scanner, "数据库IP", ValidationConstants.IP_PATTERNS, ValueType.REQUIRE_SINGLE,
					ds.getIp());
			String port = scanner(scanner, "端口", ValidationConstants.PORT_PATTERNS, ValueType.REQUIRE_SINGLE,
					ds.getPort());

			String user = ask(scanner, "用户名", ValueType.REQUIRE_SINGLE, ds.getUsername());
			String pwd = ask(scanner, "密码", ValueType.REQUIRE_SINGLE);

			if (StringUtils.isBlank(pwd))
				continue;

			Connection[] holder = new Connection[1];
			String dbName = selectOrCreateDbWorkflow(ds, scanner, holder);
			if (dbName != null) {
				ds.setDriverClassName(dbType.getDriverClassName());
				ds.setUrl(dbType.buildUrl(ip, port, dbName));
				ds.setUsername(user);
				ds.setPassword(pwd);
				ds.init();
				return false;
			}
		}
		System.err.println("无法连接数据库，退出。");
		System.exit(1);
		return false;
	}

	private static String selectOrCreateDbWorkflow(DataSourceConf ds, Scanner scanner, Connection[] holder) {
		if (ds.getDBType() == DBType.ORACLE)
			return ask(scanner, "Oracle服务名", ValueType.REQUIRE_SINGLE, "orcl");
		// 查询所有数据库名
		List<String> dbs = ds.getDataBaseNames();
		System.out.println("可用数据库: " + String.join(", ", dbs));
		String input = ask(scanner, "选择数据库 (序号/名称, 回车自动创建)", ValueType.NOT_REQUIRE_SINGLE, "");

		if (StringUtils.isBlank(input)) {
			String newDb = "db_" + LocalDateTime.now().format(DateTimeFormatter.ofPattern("MMddHHmm"));
			if (ds.createDatabase(newDb)) {
				return newDb;
			}
			return null;
		}
		try {
			int idx = Integer.parseInt(input) - 1;
			String dbName = (idx >= 0 && idx < dbs.size()) ? dbs.get(idx) : input;
			ds.setDbName(dbName);
			// 空数据库则导入sql
			if (ds.isEmptyDataBase()) {
				ds.importSql(scanSqlFilesInExamples());
			}
			return dbName;
		} catch (NumberFormatException e) {
			return input;
		}
	}

	private static void selectComponentPreset(GlobalConf global, Scanner scanner) {
		System.out.println("选择组件套装:");
		System.out.println("1. 标准版 (前后端)");
		System.out.println("2. 全家桶 (含 APM)");
		String choice = ask(scanner, "选择序号", ValueType.REQUIRE_SINGLE, "1", "2");
		String preset = ValidationConstants.COMPONENT_PRESETS[Integer.parseInt(choice) - 1];
		global.setComponents(Arrays.stream(preset.split(",")).map(Component::getComponent).toArray(Component[]::new));
	}

	private static boolean executeAllSqlScripts(Connection conn) {
		List<String> files = scanSqlFilesInExamples();
		if (files.isEmpty())
			return false;
		Collections.sort(files);
		for (String f : files) {
			try (InputStream is = CmdGenerator.class.getClassLoader().getResourceAsStream("examples/" + f)) {
				String sql = IOUtils.toString(is, StandardCharsets.UTF_8);
				conn.createStatement().execute(sql);
				System.out.println("成功执行脚本: " + f);
			} catch (Exception e) {
				System.err.println("脚本失败: " + f + " -> " + e.getMessage());
				return false;
			}
		}
		return true;
	}

	private static List<String> scanSqlFilesInExamples() {
		List<String> sqlFiles = new ArrayList<>();
		try {
			Enumeration<URL> resources = CmdGenerator.class.getClassLoader().getResources("examples");
			while (resources.hasMoreElements()) {
				URL res = resources.nextElement();
				if ("file".equals(res.getProtocol())) {
					java.io.File dir = new java.io.File(res.toURI());
					String[] list = dir.list((d, name) -> name.toLowerCase().endsWith(".sql"));
					if (list != null)
						sqlFiles.addAll(Arrays.asList(list));
				} else if ("jar".equals(res.getProtocol())) {
					String path = res.getPath();
					int split = path.indexOf("!");
					if (split < 0)
						continue;
					String jarPath = path.substring(5, split);
					try (java.util.jar.JarFile jar = new java.util.jar.JarFile(jarPath)) {
						Enumeration<java.util.jar.JarEntry> entries = jar.entries();
						while (entries.hasMoreElements()) {
							String name = entries.nextElement().getName();
							if (name.startsWith("examples/") && name.endsWith(".sql")) {
								sqlFiles.add(name.substring(name.lastIndexOf("/") + 1));
							}
						}
					}
				}
			}
		} catch (Exception e) {
			logger.error("扫描 SQL 失败", e);
		}
		return sqlFiles;
	}

	private static void executeGeneration(Generator generator) {
		try {
			System.out.println("\n>>> 配置就绪，开始生成...");
			long start = System.currentTimeMillis();
			generator.execute();
			System.out.println("\n[完成] 耗时：" + (System.currentTimeMillis() - start) + "ms");
		} catch (Exception e) {
			logger.error("代码生成失败:", e);
			System.exit(1);
		}
	}

	private static Map<String, String> parseArgs(String[] args) {
		Map<String, String> map = new HashMap<>();
		if (args == null)
			return map;
		for (int i = 0; i < args.length; i++) {
			if (args[i].startsWith("--")) {
				String val = (i + 1 < args.length && !args[i + 1].startsWith("--")) ? args[++i] : null;
				map.put(args[i - (val == null ? 0 : 1)], val);
			}
		}
		return map;
	}

	private static void applyCommandLineArgsToDataSource(DataSourceConf ds, Map<String, String> argMap) {
		String pwd = argMap.get(ARG_DB_PASSWORD);
		if (StringUtils.isNotBlank(pwd))
			ds.setEncryptedPassword(pwd);
	}

	private static void displayWelcomeMessage() {
		try (InputStream is = CmdGenerator.class.getResourceAsStream("/welcome.txt")) {
			if (is != null)
				IOUtils.readLines(is, StandardCharsets.UTF_8).forEach(System.err::println);
		} catch (IOException ignored) {
		}
	}

	private static void printHelp() {
		System.out.println("用法: ./startup.sh --quick --db-password <password>");
	}

	/**
	 * 简单询问 (无正则验证)
	 */
	private static String ask(Scanner scanner, String tip, ValueType valType, String... defaults) {
		return scanner(scanner, tip, null, valType, defaults);
	}

	/**
	 * 核心询问方法 (带正则验证)
	 */
	private static String scanner(Scanner scanner, String tip, String[] regex, ValueType valType, String... defaults) {
		String dInfo = (defaults != null && defaults.length > 0) ? " [" + String.join("/", defaults) + "]" : "";
		System.out.print(tip + (valType.isRequired() ? "(*)" : "") + dInfo + ": ");

		while (scanner.hasNextLine()) {
			String input = scanner.nextLine().trim();
			if (StringUtils.isBlank(input)) {
				if (valType.isRequired() && (defaults == null || defaults.length == 0))
					continue;
				return (defaults != null && defaults.length > 0)
						? (valType.isSingle() ? defaults[0] : String.join(",", defaults))
						: "";
			}
			// 正则校验
			if (regex == null || Arrays.stream(regex).anyMatch(input::matches)) {
				return input;
			}
			System.out.print("输入格式错误，请重新输入 " + dInfo + ": ");
		}
		return (defaults != null && defaults.length > 0) ? defaults[0] : "";
	}
}
