<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.linghang</groupId>
    <artifactId>linghang-platform</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>
    <name>linghang-platform</name>
    <description>通用金融交易中台系统</description>

    <modules>
        <module>core</module>
        <module>common</module>
        <module>gateway-service</module>
        <module>domain-services</module>
        <module>sense-service</module>
        <module>admin-service</module>
        <module>task-service</module>
    </modules>

    <properties>
        <revision>1.0.0</revision>
        <java.version>21</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>

        <spring-boot.version>3.2.4</spring-boot.version>
        <spring-cloud.version>2023.0.1</spring-cloud.version>
        <spring-cloud-alibaba.version>2023.0.1.0</spring-cloud-alibaba.version>
        <dubbo.version>3.3.2</dubbo.version>
        <mybatis-plus.version>3.5.5</mybatis-plus.version>
        <mybatis.version>3.5.15</mybatis.version>
        <mysql.version>8.0.33</mysql.version>
        <druid.version>1.2.27</druid.version>
        <rocketmq.starter.version>2.3.0</rocketmq.starter.version>
        <skywalking.version>9.4.0</skywalking.version>
        <lombok.version>1.18.30</lombok.version>
        <hutool.version>5.8.26</hutool.version>
        <jjwt.version>0.12.5</jjwt.version>
        <sentinel.version>1.8.8</sentinel.version>
        <easyexcel.version>4.0.3</easyexcel.version>
        <jasypt.version>3.0.5</jasypt.version>
        <springdoc.version>2.5.0</springdoc.version>
        <swagger-core.version>2.2.21</swagger-core.version>
        <fastjson2.version>2.0.58</fastjson2.version>
        <bouncycastle.version>1.78.1</bouncycastle.version>
        <okhttp.version>4.12.0</okhttp.version>
        <minio.version>8.5.7</minio.version>
        
        <versions-maven-plugin.version>2.16.2</versions-maven-plugin.version>
        <flatten-maven-plugin.version>1.6.0</flatten-maven-plugin.version>
        <dependency-check-maven.version>10.0.2</dependency-check-maven.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>${spring-cloud-alibaba.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>org.apache.dubbo</groupId>
                <artifactId>dubbo-bom</artifactId>
                <version>${dubbo.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- MyBatis Plus -->
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-spring-boot3-starter</artifactId>
                <version>${mybatis-plus.version}</version>
            </dependency>
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-annotation</artifactId>
                <version>${mybatis-plus.version}</version>
            </dependency>

            <!-- Database -->
            <dependency>
                <groupId>com.mysql</groupId>
                <artifactId>mysql-connector-j</artifactId>
                <version>${mysql.version}</version>
            </dependency>
            <dependency>
                <groupId>org.mybatis</groupId>
                <artifactId>mybatis</artifactId>
                <version>${mybatis.version}</version>
            </dependency>
            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>druid-spring-boot-3-starter</artifactId>
                <version>${druid.version}</version>
            </dependency>

            <!-- RocketMQ -->
            <dependency>
                <groupId>org.apache.rocketmq</groupId>
                <artifactId>rocketmq-spring-boot-starter</artifactId>
                <version>${rocketmq.starter.version}</version>
            </dependency>

            <!-- SkyWalking -->
            <dependency>
                <groupId>org.apache.skywalking</groupId>
                <artifactId>apm-toolkit-trace</artifactId>
                <version>${skywalking.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.skywalking</groupId>
                <artifactId>apm-toolkit-logback-1.x</artifactId>
                <version>${skywalking.version}</version>
            </dependency>

            <!-- Utilities -->
            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
            </dependency>
            <dependency>
                <groupId>cn.hutool</groupId>
                <artifactId>hutool-all</artifactId>
                <version>${hutool.version}</version>
            </dependency>
            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>easyexcel</artifactId>
                <version>${easyexcel.version}</version>
            </dependency>
            <dependency>
                <groupId>com.github.ulisesbocchio</groupId>
                <artifactId>jasypt-spring-boot-starter</artifactId>
                <version>${jasypt.version}</version>
            </dependency>
            <dependency>
                <groupId>com.alibaba.fastjson2</groupId>
                <artifactId>fastjson2-extension-spring6</artifactId>
                <version>${fastjson2.version}</version>
            </dependency>

            <!-- Bouncy Castle -->
            <dependency>
                <groupId>org.bouncycastle</groupId>
                <artifactId>bcprov-jdk18on</artifactId>
                <version>${bouncycastle.version}</version>
            </dependency>

            <!-- OkHttp -->
            <dependency>
                <groupId>com.squareup.okhttp3</groupId>
                <artifactId>okhttp</artifactId>
                <version>${okhttp.version}</version>
            </dependency>

            <!-- Minio -->
            <dependency>
                <groupId>io.minio</groupId>
                <artifactId>minio</artifactId>
                <version>${minio.version}</version>
            </dependency>

            <!-- JWT -->
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-api</artifactId>
                <version>${jjwt.version}</version>
            </dependency>
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-impl</artifactId>
                <version>${jjwt.version}</version>
            </dependency>
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-jackson</artifactId>
                <version>${jjwt.version}</version>
            </dependency>

            <!-- API Docs -->
            <dependency>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
                <version>${springdoc.version}</version>
            </dependency>
            <dependency>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-starter-webflux-ui</artifactId>
                <version>${springdoc.version}</version>
            </dependency>
            <dependency>
                <groupId>io.swagger.core.v3</groupId>
                <artifactId>swagger-annotations-jakarta</artifactId>
                <version>${swagger-core.version}</version>
            </dependency>

            <!-- Internal Modules -->
            <dependency>
                <groupId>com.linghang</groupId>
                <artifactId>core</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.linghang</groupId>
                <artifactId>common</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.linghang</groupId>
                <artifactId>user-api</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.linghang</groupId>
                <artifactId>content-api</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.linghang</groupId>
                <artifactId>wallet-api</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.linghang</groupId>
                <artifactId>challenge-api</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.linghang</groupId>
                <artifactId>order-api</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.linghang</groupId>
                <artifactId>strategy-api</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.linghang</groupId>
                <artifactId>invite-api</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.linghang</groupId>
                <artifactId>web3-api</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.linghang</groupId>
                <artifactId>message-api</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.linghang</groupId>
                <artifactId>payment-api</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.linghang</groupId>
                <artifactId>file-service</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.linghang</groupId>
                <artifactId>risk-api</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.linghang</groupId>
                <artifactId>event-api</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.linghang</groupId>
                <artifactId>activity-api</artifactId>
                <version>${revision}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.12.1</version>
                    <configuration>
                        <release>${java.version}</release>
                        <proc>full</proc>
                        <encoding>${project.build.sourceEncoding}</encoding>
                        <compilerArgs>
                            <arg>-parameters</arg>
                        </compilerArgs>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                    <version>${spring-boot.version}</version>
                    <executions>
                        <execution>
                            <goals>
                                <goal>repackage</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>versions-maven-plugin</artifactId>
                    <version>${versions-maven-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>flatten-maven-plugin</artifactId>
                    <version>${flatten-maven-plugin.version}</version>
                    <configuration>
                        <updatePomFile>true</updatePomFile>
                        <flattenMode>resolveCiFriendliesOnly</flattenMode>
                    </configuration>
                    <executions>
                        <execution>
                            <id>flatten</id>
                            <phase>initialize</phase>
                            <goals>
                                <goal>flatten</goal>
                            </goals>
                        </execution>
                        <execution>
                            <id>flatten.clean</id>
                            <phase>clean</phase>
                            <goals>
                                <goal>clean</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <!-- OWASP Dependency Check 安全漏洞扫描插件 -->
                <plugin>
                    <groupId>org.owasp</groupId>
                    <artifactId>dependency-check-maven</artifactId>
                    <version>${dependency-check-maven.version}</version>
                    <configuration>
                        <failBuildOnCVSS>7</failBuildOnCVSS>
                        <skipTestScope>true</skipTestScope>
                        <format>HTML</format>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>dev</id>
            <properties>
                <profile.active>dev</profile.active>
            </properties>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
        </profile>
        <profile>
            <id>prod</id>
            <properties>
                <profile.active>prod</profile.active>
            </properties>
        </profile>
    </profiles>
</project>
